# Generated by Django 2.2.5 on 2019-09-12 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tees', '0002_auto_20190911_0250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teesdata',
            old_name='create_uid',
            new_name='owner',
        ),
    ]
