# Generated by Django 2.2.5 on 2019-09-12 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tees', '0003_auto_20190912_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='teesdata',
            name='email',
            field=models.EmailField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='teesdata',
            name='name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='teesdata',
            name='size',
            field=models.CharField(blank=True, choices=[('sm', 'SMALL'), ('md', 'MEDIUM'), ('lg', 'LARGE'), ('xl', 'EXTRA LARGE')], default='sm', max_length=50),
        ),
    ]
