# Generated by Django 2.2.5 on 2019-09-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tees', '0004_auto_20190912_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teesdata',
            name='email',
            field=models.EmailField(max_length=150),
        ),
        migrations.AlterField(
            model_name='teesdata',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
